alter table domains 
add   `site_width` int(11) NOT NULL,
add   `site_alignment` varchar(255) default NULL,
add   `sitebackgroundimage_id` int(11) default NULL COMMENT 'attachments',
add   `site_background_color` varchar(255) default NULL,
add   `headerimage_id` int(11) default NULL COMMENT 'attachments',
add   `header_image_link` varchar(255) default NULL,
add   `topmenubackgroundimage_id` int(11) default NULL COMMENT 'attachments',
add   `top_menu_background_color` varchar(255) default NULL,
add   `bottommenubackgroundimage_id` int(11) default NULL COMMENT 'attachments',
add   `bottom_menu_background_color` varchar(25) default NULL,
add   `site_border_left_color` varchar(255) default NULL,
add   `site_border_left_size_px` int(11) default NULL,
add   `site_border_right_color` varchar(255) default NULL,
add   `site_border_right_size_px` int(11) default NULL,
add   `site_border_top_color` varchar(255) default NULL,
add   `site_border_top_size_px` int(11) default NULL,
add   `site_border_bottom_color` varchar(255) default NULL,
add   `site_border_bottom_size_px` int(255) default NULL,
add   `table_heading_background_color` varchar(255) default NULL,
add   `site_font_type` varchar(255) default NULL,
add   `h1_color` varchar(255) default NULL,
add   `h1_size` int(11) default NULL,
add   `h2_color` varchar(255) default NULL,
add   `h2_size` int(11) default NULL,
add   `h3_color` varchar(255) default NULL,
add   `h3_size` int(11) default NULL,
add   `a_color` varchar(255) default NULL,
add   `a_size` int(11) default NULL,
add   `a_hover_color` varchar(255) default NULL,
add   `a_hover_size` int(11) default NULL,
add   `topmenu_color` varchar(255) default NULL,
add   `topmenu_size` int(11) default NULL,
add   `topmenulink_color` varchar(255) default NULL,
add   `topmenulink_size` int(11) default NULL,
add   `topmenulink_hover_color` varchar(255) default NULL,
add   `topmenulink_hover_size` int(11) default NULL,
add   `bottommenu_color` varchar(255) default NULL,
add   `bottommenu_size` int(11) default NULL,
add   `bottommenulink_color` varchar(255) default NULL,
add   `bottommenulink_size` int(11) default NULL,
add   `bottommenulink_hover_color` varchar(255) default NULL,
add   `bottommenulink_hover_size` int(11) default NULL,
add   `footertext_color` varchar(255) default NULL,
add   `footertext_size` int(11) default NULL,
add   `footertextlink_color` varchar(255) default NULL,
add   `footertextlink_size` int(11) default NULL,
add   `footertextlink_hover_color` varchar(255) default NULL,
add   `footertextlink_hover_size` int(11) default NULL,
add   `bodytext_color` varchar(255) default NULL,
add   `bodytext_size` int(11) default NULL,
add   `header_height` int(11) default NULL,
add   `footer_background_color` varchar(255) default NULL,
add   `top_menu_height` int(11) default NULL,
add   `bottom_menu_height` int(11) default NULL
;
